name: Draw Keymap
on:
  push:
    branches:
      - main
    paths:
      - config/corne.keymap
  workflow_dispatch:

jobs:
  draw:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
    permissions:
      contents: write
    with:
      keymap_patterns: config/corne.keymap
      config_path: keymap_drawer.config.yaml
      west_config_path: config
      output_folder: keymap-drawer